### ISSUE TITLE
Divider and Bookmarks Issue

### ISSUE THREAD

**Issue by vamsi3001** [TryGhost/London#40]
Divider and Bookmarks looks broken. Divider, not sure if it's expected output and Bookmarks the Card layout is broken. 

Editor Mode
<img width="888" alt="Screenshot 2019-12-27 at 5 41 58 PM" src="https://user-images.githubusercontent.com/13076901/71516796-f65fbf00-28d0-11ea-9cb9-5ff3ea4086b6.png">

Preview Mode
<img width="888" alt="Screenshot 2019-12-27 at 5 42 04 PM" src="https://user-images.githubusercontent.com/13076901/71516797-f65fbf00-28d0-11ea-9b66-6523bafe29da.png">

**Comment by minimaluminium** [comment]
Hey @vamsi3001, sorry about the delay! The divider line issue was fixed in 9e7c6e1. For the bookmark issue, can you please make sure you're using the latest version of the theme from the master repo? The bookmark styles have already been added in https://github.com/TryGhost/London/commit/bbc4bb6c9cb6b80dee1b5c22cfb40466e2f33cc0.
